// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvqlromwiejgcnnvzdat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cWxyb213aWVqZ2NubnZ6ZGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNjc1MTMsImV4cCI6MjA2Njc0MzUxM30.M95aYd4vrOdeCyf6WBWyrSJ96nBjz5NBTAd-v2ZtYm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);